if(NOT DEFINED PROGRAM OR NOT DEFINED CASE OR NOT DEFINED INPUT OR NOT DEFINED WORK)
    message(FATAL_ERROR "PROGRAM, CASE, INPUT and WORK are required")
endif()
file(MAKE_DIRECTORY "${WORK}")
set(common --cols 16 --rows 8 --fast --no-audio)
if(CASE STREQUAL "collision")
    set(target "${WORK}/collision.mkv")
    configure_file("${INPUT}" "${target}" COPYONLY)
    file(SHA256 "${target}" before)
    execute_process(COMMAND "${PROGRAM}" "${target}" ${common} -o "${target}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    file(SHA256 "${target}" after)
    if(result EQUAL 0 OR NOT before STREQUAL after OR NOT stderr MATCHES "paths must be distinct")
        message(FATAL_ERROR "Source/output collision was accepted or modified input: ${stderr}")
    endif()
elseif(CASE STREQUAL "numbered-collision")
    foreach(index 0 5)
        set(target "${WORK}/collision_${index}.txt")
        file(WRITE "${target}" "existing replay")
        execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
            -o "${WORK}/collision.txt" --replay "${target}"
            RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
        file(READ "${target}" bytes)
        if(result EQUAL 0 OR NOT bytes STREQUAL "existing replay" OR
           NOT stderr MATCHES "paths must be distinct")
            message(FATAL_ERROR "Numbered text/replay collision was accepted: ${stderr}")
        endif()
    endforeach()
elseif(CASE STREQUAL "replay-numbered-collision")
    set(target "${WORK}/collision_0.txt")
    configure_file("${INPUT}" "${target}" COPYONLY)
    file(SHA256 "${target}" before)
    execute_process(COMMAND "${PROGRAM}" --play-replay "${target}" -o "${WORK}/collision.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    file(SHA256 "${target}" after)
    if(result EQUAL 0 OR NOT before STREQUAL after OR NOT stderr MATCHES "paths must be distinct")
        message(FATAL_ERROR "Numbered replay text collision was accepted: ${stderr}")
    endif()
elseif(CASE STREQUAL "preserve")
    set(target "${WORK}/preserve.mkv")
    set(replay "${WORK}/preserve.areplay")
    file(WRITE "${target}" "existing video")
    file(WRITE "${replay}" "existing replay")
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
        -o "${target}" --replay "${replay}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    file(READ "${target}" video_bytes)
    file(READ "${replay}" replay_bytes)
    if(result EQUAL 0 OR NOT video_bytes STREQUAL "existing video" OR
       NOT replay_bytes STREQUAL "existing replay")
        message(FATAL_ERROR "Failed decode replaced an existing output: ${stderr}")
    endif()
elseif(CASE STREQUAL "destination-directory")
    foreach(kind replay bmp mp4 txt)
        set(target "${WORK}/directory.${kind}")
        file(MAKE_DIRECTORY "${target}")
        if(kind STREQUAL "replay")
            set(preserved "${WORK}/existing.bmp")
            set(destinations --replay "${target}" -o "${preserved}")
        else()
            set(preserved "${WORK}/existing.areplay")
            set(destinations -o "${target}" --replay "${preserved}")
        endif()
        file(WRITE "${preserved}" "existing destination")
        execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common} ${destinations}
            RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
        file(READ "${preserved}" bytes)
        if(result EQUAL 0 OR NOT bytes STREQUAL "existing destination" OR
           NOT stderr MATCHES "destination is a directory" OR stderr MATCHES "\\[PERF\\]")
            message(FATAL_ERROR "Directory ${kind} destination was not rejected before processing: ${stderr}")
        endif()
    endforeach()
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
        --replay "${WORK}/valid.areplay" -o "${WORK}/valid.txt"
        RESULT_VARIABLE prepared OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT prepared EQUAL 0)
        message(FATAL_ERROR "Replay directory-check fixture failed: ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" --play-replay "${WORK}/valid.areplay"
        -o "${WORK}/directory.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(result EQUAL 0 OR NOT stderr MATCHES "destination is a directory")
        message(FATAL_ERROR "Replay text directory destination was accepted: ${stderr}")
    endif()
elseif(CASE STREQUAL "sequence-collision")
    set(fixture "${WORK}/fixture.bmp")
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common} -o "${fixture}"
        RESULT_VARIABLE prepared OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT prepared EQUAL 0)
        message(FATAL_ERROR "Sequence collision fixture failed: ${stderr}")
    endif()
    file(SHA256 "${fixture}" before)
    set(failures "")
    foreach(kind still replay numbered)
        set(directory "${WORK}/${kind}")
        file(MAKE_DIRECTORY "${directory}")
        set(extension bmp)
        if(kind STREQUAL "numbered")
            set(extension txt)
        endif()
        foreach(index 0 1)
            configure_file("${fixture}" "${directory}/frame_${index}.${extension}" COPYONLY)
        endforeach()
        if(kind STREQUAL "still")
            set(destinations -o "${directory}/frame_1.bmp")
        elseif(kind STREQUAL "replay")
            set(destinations --replay "${directory}/frame_1.bmp" -o "${WORK}/replay.txt")
        else()
            set(destinations -o "${directory}/frame.txt")
        endif()
        execute_process(COMMAND "${PROGRAM}" "${directory}/frame_*.${extension}" ${common} ${destinations}
            RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
        foreach(index 0 1)
            file(SHA256 "${directory}/frame_${index}.${extension}" after)
            if(result EQUAL 0 OR NOT before STREQUAL after OR NOT stderr MATCHES "paths must be distinct")
                list(APPEND failures "${kind} frame ${index}: exit=${result}, preserved=${after}, expected=${before}")
            endif()
        endforeach()
    endforeach()
    if(failures)
        message(FATAL_ERROR "Sequence source/output collisions were not rejected: ${failures}")
    endif()
elseif(CASE STREQUAL "unicode-paths")
    set(unicode_directory "${WORK}/Δοκιμή影像")
    file(MAKE_DIRECTORY "${unicode_directory}")
    set(image "${unicode_directory}/εικόνα画像.png")
    set(video "${unicode_directory}/βίντεο動画.mkv")
    configure_file("${CMAKE_CURRENT_LIST_DIR}/../images/potsepis.png" "${image}" COPYONLY)
    configure_file("${INPUT}" "${video}" COPYONLY)

    execute_process(COMMAND "${PROGRAM}" "${CMAKE_CURRENT_LIST_DIR}/../images/potsepis.png"
        ${common} --color none -o "${WORK}/reference.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "ASCII reference image failed: ${stderr}")
    endif()
    set(image_text "${unicode_directory}/κείμενο文字.txt")
    set(image_replay "${unicode_directory}/επανάληψη再生.areplay")
    execute_process(COMMAND "${PROGRAM}" "${image}" ${common} --color none
        --replay "${image_replay}" -o "${image_text}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode image/text/replay paths failed: ${stderr}")
    endif()
    file(SHA256 "${WORK}/reference.txt" reference_hash)
    file(SHA256 "${image_text}" image_hash)
    if(NOT reference_hash STREQUAL image_hash)
        message(FATAL_ERROR "Unicode filename changed image text output")
    endif()
    execute_process(COMMAND "${PROGRAM}" --inspect-replay "${image_replay}"
        RESULT_VARIABLE result OUTPUT_VARIABLE info ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0 OR NOT info MATCHES "frames: 1")
        message(FATAL_ERROR "Unicode image replay inspection failed: ${info} ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" --play-replay "${image_replay}"
        -o "${unicode_directory}/ανάγνωση読取.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode replay text export failed: ${stderr}")
    endif()
    file(SHA256 "${unicode_directory}/ανάγνωση読取.txt" replay_text_hash)
    if(NOT reference_hash STREQUAL replay_text_hash)
        message(FATAL_ERROR "Unicode replay text differs from image text")
    endif()

    set(bitmap "${unicode_directory}/εικόνα画像.bmp")
    execute_process(COMMAND "${PROGRAM}" "${image}" ${common} --color none -o "${bitmap}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode BMP output failed: ${stderr}")
    endif()
    execute_process(COMMAND "${MEDIA_HELPER}" verify-monochrome "${bitmap}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode BMP decode/content verification failed: ${stderr}")
    endif()
    file(SHA256 "${bitmap}" bitmap_hash)
    file(WRITE "${unicode_directory}/ρυθμίσεις設定.toml" "[color]\nmode = \"none\"\n")
    execute_process(COMMAND "${PROGRAM}" "${image}" ${common}
        --config "${unicode_directory}/ρυθμίσεις設定.toml" -o "${unicode_directory}/ρυθμισμένη設定.bmp"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode configuration path failed: ${stderr}")
    endif()
    file(SHA256 "${unicode_directory}/ρυθμισμένη設定.bmp" configured_hash)
    if(NOT bitmap_hash STREQUAL configured_hash)
        message(FATAL_ERROR "Unicode configuration was ignored or changed rendered output")
    endif()
    if(EXISTS "$ENV{WINDIR}/Fonts/consola.ttf")
        set(font "$ENV{WINDIR}/Fonts/consola.ttf")
        configure_file("${font}" "${unicode_directory}/γραμματοσειρά字体.ttf" COPYONLY)
        foreach(variant original unicode)
            set(selected_font "${font}")
            if(variant STREQUAL "unicode")
                set(selected_font "${unicode_directory}/γραμματοσειρά字体.ttf")
            endif()
            execute_process(COMMAND "${PROGRAM}" "${image}" ${common} --color none
                --font "${selected_font}" -o "${unicode_directory}/font-${variant}.bmp"
                RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
            if(NOT result EQUAL 0)
                message(FATAL_ERROR "${variant} font filename failed: ${stderr}")
            endif()
            file(SHA256 "${unicode_directory}/font-${variant}.bmp" font_${variant}_hash)
        endforeach()
        if(NOT font_original_hash STREQUAL font_unicode_hash)
            message(FATAL_ERROR "Unicode font filename changed rendered output")
        endif()
    else()
        message(STATUS "Consolas fixture unavailable; Unicode font-path check skipped")
    endif()

    set(encoded "${unicode_directory}/εξαγωγή出力.mkv")
    set(video_replay "${unicode_directory}/κίνηση動画.areplay")
    execute_process(COMMAND "${PROGRAM}" "${video}" ${common} --color none
        --replay "${video_replay}" -o "${encoded}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode video input/output paths failed: ${stderr}")
    endif()
    execute_process(COMMAND "${MEDIA_HELPER}" verify-video "${encoded}" 8 30
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode encoded video frame/EOF verification failed: ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" --inspect-replay "${video_replay}"
        RESULT_VARIABLE result OUTPUT_VARIABLE info ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0 OR NOT info MATCHES "frames: 8")
        message(FATAL_ERROR "Unicode video replay inspection failed: ${info} ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" --play-replay "${video_replay}"
        -o "${unicode_directory}/καρέ再生.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode numbered replay export failed: ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" "${video}" ${common} --color none
        -o "${unicode_directory}/καρέ直接.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode numbered text export failed: ${stderr}")
    endif()
    foreach(index RANGE 0 7)
        file(SHA256 "${unicode_directory}/καρέ再生_${index}.txt" replay_hash)
        file(SHA256 "${unicode_directory}/καρέ直接_${index}.txt" direct_hash)
        if(NOT replay_hash STREQUAL direct_hash)
            message(FATAL_ERROR "Unicode replay/direct text frame ${index} differs")
        endif()
    endforeach()

    set(sequence "${unicode_directory}/σειρά連続")
    file(MAKE_DIRECTORY "${sequence}")
    foreach(index 0 1)
        configure_file("${bitmap}" "${sequence}/καρέ画像_${index}.bmp" COPYONLY)
    endforeach()
    execute_process(COMMAND "${PROGRAM}" "${sequence}/καρέ画像_*.bmp" ${common}
        --replay "${unicode_directory}/σειρά連続.areplay" -o "${unicode_directory}/σειρά連続.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode wildcard image sequence failed: ${stderr}")
    endif()
    execute_process(COMMAND "${MEDIA_HELPER}" verify-text "${unicode_directory}/σειρά連続.txt" 2
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT result EQUAL 0)
        message(FATAL_ERROR "Unicode wildcard sequence frame verification failed: ${stderr}")
    endif()
    file(SHA256 "${video}" video_hash)
    execute_process(COMMAND "${PROGRAM}" "${video}" ${common} -o "${video}"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    file(SHA256 "${video}" after_hash)
    if(result EQUAL 0 OR NOT video_hash STREQUAL after_hash OR NOT stderr MATCHES "paths must be distinct")
        message(FATAL_ERROR "Unicode direct input/output collision was accepted or changed input: ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" "${sequence}/καρέ画像_*.bmp" ${common}
        -o "${sequence}/καρέ画像_1.bmp"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    if(result EQUAL 0 OR NOT stderr MATCHES "paths must be distinct")
        message(FATAL_ERROR "Unicode sequence input/output collision was accepted: ${stderr}")
    endif()
    foreach(index 0 1)
        file(SHA256 "${sequence}/καρέ画像_${index}.bmp" after_hash)
        if(NOT bitmap_hash STREQUAL after_hash)
            message(FATAL_ERROR "Unicode sequence collision changed input ${index}")
        endif()
    endforeach()
elseif(CASE STREQUAL "config-color")
    file(WRITE "${WORK}/none.toml" "[color]\nmode = \"none\"\n")
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
        --config "${WORK}/none.toml" -o "${WORK}/config.bmp"
        RESULT_VARIABLE configured OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
        --color none -o "${WORK}/cli.bmp"
        RESULT_VARIABLE explicit OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT configured EQUAL 0 OR NOT explicit EQUAL 0)
        message(FATAL_ERROR "Color configuration export failed: ${stderr}")
    endif()
    file(SHA256 "${WORK}/config.bmp" configured_hash)
    file(SHA256 "${WORK}/cli.bmp" explicit_hash)
    if(NOT configured_hash STREQUAL explicit_hash)
        message(FATAL_ERROR "Explicit config color none differs from CLI color none")
    endif()
elseif(CASE STREQUAL "debug-replay")
    file(WRITE "${WORK}/stdin.txt" "")
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
        --debug grayscale --replay "${WORK}/debug.areplay"
        INPUT_FILE "${WORK}/stdin.txt"
        RESULT_VARIABLE result OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT result EQUAL 0 OR NOT EXISTS "${WORK}/debug.areplay")
        message(FATAL_ERROR "Debug rendering did not produce replay: ${stderr}")
    endif()
    execute_process(COMMAND "${PROGRAM}" --inspect-replay "${WORK}/debug.areplay"
        RESULT_VARIABLE inspected OUTPUT_VARIABLE info ERROR_VARIABLE stderr TIMEOUT 10)
    if(NOT inspected EQUAL 0 OR NOT info MATCHES "frames: 1")
        message(FATAL_ERROR "Debug replay has no rendered frame: ${info} ${stderr}")
    endif()
    if(stdout MATCHES "Press Enter")
        message(FATAL_ERROR "Redirected image output requested interactive input")
    endif()
    execute_process(COMMAND "${PROGRAM}" --play-replay "${WORK}/debug.areplay"
        -o "${WORK}/terminal-debug.txt"
        RESULT_VARIABLE decoded OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
    execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common} --debug grayscale
        -o "${WORK}/export-debug.txt"
        RESULT_VARIABLE exported OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
    if(NOT decoded EQUAL 0 OR NOT exported EQUAL 0)
        message(FATAL_ERROR "Debug text comparison failed: ${stderr}")
    endif()
    file(SHA256 "${WORK}/terminal-debug.txt" terminal_hash)
    file(SHA256 "${WORK}/export-debug.txt" export_hash)
    if(NOT terminal_hash STREQUAL export_hash)
        message(FATAL_ERROR "Debug view is ignored during file export")
    endif()
    foreach(mode grayscale edges orientation)
        foreach(charset basic blocks line-art)
            set(bitmap "${WORK}/${mode}-${charset}.bmp")
            execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
                --color none --debug ${mode} --char-set ${charset} -o "${bitmap}"
                RESULT_VARIABLE rendered OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
            if(NOT rendered EQUAL 0)
                message(FATAL_ERROR "Debug bitmap export failed: ${stderr}")
            endif()
            file(SHA256 "${bitmap}" bitmap_hash)
            if(charset STREQUAL "basic")
                set(reference_hash "${bitmap_hash}")
            elseif(NOT bitmap_hash STREQUAL reference_hash)
                message(FATAL_ERROR "Debug ${mode} bitmap depends on selectable charset ${charset}")
            endif()
            execute_process(COMMAND "${MEDIA_HELPER}" verify-monochrome "${bitmap}"
                RESULT_VARIABLE monochrome OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
            if(NOT monochrome EQUAL 0)
                message(FATAL_ERROR "Debug ${mode} ignored color none: ${stderr}")
            endif()
        endforeach()
    endforeach()
    foreach(colors 16 256)
        set(replay "${WORK}/orientation-${colors}.areplay")
        execute_process(COMMAND "${PROGRAM}" "${INPUT}" ${common}
            --debug orientation --color ${colors} --replay "${replay}" -o "${WORK}/palette.txt"
            RESULT_VARIABLE rendered OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 30)
        execute_process(COMMAND "${MEDIA_HELPER}" verify-replay-palette "${replay}" ${colors}
            RESULT_VARIABLE palette OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr TIMEOUT 10)
        if(NOT rendered EQUAL 0 OR NOT palette EQUAL 0)
            message(FATAL_ERROR "Debug view ignored ${colors}-color palette: ${stderr}")
        endif()
    endforeach()
else()
    message(FATAL_ERROR "Unknown runtime contract: ${CASE}")
endif()
